/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kamimura' at '16/05/19 10:08' with Gradle 2.12
 *
 * @author kamimura, @date 16/05/19 10:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
