/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'seamark' at '16/09/29 13:13' with Gradle 2.14.1
 *
 * @author seamark, @date 16/09/29 13:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
